---
- name: enable ntpd
  service: name=ntpd state=running enabled=yes

- name: configure ntpd
  template: src=templates/ntp.conf.j2 dest=/etc/ntp.conf owner=root group=root mode=0644
  notify:
    - restart ntpd
